### ISSUE TITLE
Use Quick Capture Project qc.project.json file rather than `data` for config

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#1153]
Older Quick Capture Projects had their configuration in the item's `data` as well as in the qc.project.json file; newer projects only use qc.project.json.  The difference between the two seems to only be that the contents of the qc.project.json file are wrapped when in `data`:
```json
{
	"application": {
            _qc.project.json contents_
	},
	"name": "qc.project.json"
}
```

solution.js only handles the older format, which means that it only swizzles the contents of `data`.  It copies whatever is (or isn't) in `data` and maintains the qc.project.json file as a resource.

With new format files, the swizzling needs to be done in the qc.project.json file because `data` is empty.

As a hotfix, we will copy qc.project.json into `data` with the appropriate wrapper.  Later, we will change solution.js to handle both formats separately.

**Comment by chris-fox** [comment]
@MikeTschudi, I would like to continue to have it behave like it did previously. When we templatize it, it is helpful for the contents of the gc.project.json to be in the data property. This is because we can use tools like arcgis assistant to do a find/replace all for things across all the templates. If this config is only stored in the item resources it makes it a little more difficult.

I think what we could fix is during deployment we don’t need to write this information to the item data, instead just swizzle it and upload it as the gc.project.json. This change would not break any existing templates as we are not changing the way the template is written.

**Comment by MikeTschudi** [comment]
@chris-fox, my only concern with making the hotfix permanent is whether or not the QC apps will stop supporting backwards compatibility for the `data` section, such as for new features.  At this time, `data` and qc.project.json are essentially identical, but that can't be guaranteed.

@shoe913 noticed that the six release solutions that use QC all have info in their data.json file; it's only with new QC projects that `data` is not used.

By copying qc.project.json into `data` while templatizing, I didn't have to make any changes to deployment.  I think that we haven't needed to templatize qc.project.json for our solutions because of backwards-compatibility support.

**Comment by chris-fox** [comment]
@MikeTschudi, I don't believe QC has made any changes to their item, will try to clarify what I am hoping to continue to see in the behavior of this item type. To my knowledge QC has never used the item data property. All of the properties that define the quick capture project have always been stored in the qc.project.json item resource, this includes the feature services that need to be discovered and templatized.

So when we originally added support for this item type I asked that the json in the qc.project.json be written to the item template's data property rather than stay stored in the resource. This was to allow us to better modify things in the template via json editing tools like ArcGIS Assistant. During deployment I then asked that the contents of the data property of the template be swizzled like we do with all other templates, but instead write it back to the item as the qc.project.json resource rather than the item data.

So in summary:

During creation
- Get the gc.project.json from the QC project, discover any dependencies and replace with variables
- Write the qc.project.json to the template's data property under a "application": property
- Copy all other resources like any other item resource

During deployment
- Swizzle the content in the template's data property
- Write the json under the data: application property to a qc.project.json resource and add to the quick capture item
- Copy all other resources from the template to the item

This is the way it behaved previously. The only bug that I see from previous versions is we were also writing the template's data property to the item's data property during deployment. This didn't cause an issue because QuickCapture doesn't do anything with the item's data property. 

I have never seen anything actually stored in a QuickCapture project's item data that was created using the QuickCapture web app. So I think we can ignore it and not write anything to this data property during deployment. If this ever changes we can address at that time.

**Comment by chris-fox** [comment]
I have been testing with your test apps (https://solutionstest.geocloud.com/qc-test/) and I am running into 2 issues.

**During Creation:**

On Teams you said the following:
“Johnathan, when you look under the hood of a solution created with the new software, you won't see the qc.project.json file as a resource in the solution.
I made the data part of QC Project be the sole source of the info in a solution:  **if a Proj has data, it's kept, otherwise, the contents of qc.project.json are written into data**; in both cases, the qc.project.json file is deleted. During deployment, the contents of data are de-templatized and written into a qc.project.json resource for the new QC Project and the data section of the Project is emptied.”

We should change this logic to never use the Project data and always use the qc.proj.json. The fact that some QuickCapture projects have item data is due to a bug in our past deployment logic. QuickCapture doesn’t use the item data and the QC Designer never writes any info to it. The source of truth for the project should always come from the qc.proj.json file. Below I have a sample QuickCapture project item where the info in the item data is different from the json in the qc.proj.json. This is because I modified the QC project after it had been deployed and as a result the item data is stale and incorrect. When deployed the image in the QC button is broken because the item data is referencing a resource that no longer exists:

https://localdeployment.maps.arcgis.com/home/item.html?id=b6d47789ce304fc1ae79844ccb8abe88

**During Deployment:**

In regards to: **"in both cases, the qc.project.json file is deleted"**. I think this is a good change. However, we have existing solutions that have the qc.project.json in the resources. What looks to be happening now is during deployment we first add the de-templatize the data and write it into the qc.project.json resource for the new QC Project. We then copy all the item resources. When a solution template has the qc.project.json as an item resource this is copied as well and overwrites the work done in the previous step and can result in a broken Quick Capture project. You can see this today with our existing Road Management solution: (3a6e7865e2e44925addfe02852da7970). When deployed the Rapid Pavement Assessment qc project is broken because the datasource references in the qc.project.json are pointing to old services.

So I think moving forward it is good to remove the qc.project.json resource from the solution template. However, for backwards compatibility I think we need to ignore the qc.project.json resource if it is one of the resources for a quick capture project.

**Comment by chris-fox** [comment]
Verified
