### ISSUE TITLE
StoryMap Collection and Briefing support

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#1209]
We have support for the item type StoryMap which was originally implemented to support the original StoryMap 'stories'. Since this time the team has introduced Collections and Briefings. All though in the portal UI it displays these as unique items in REST these three things are all an item type "StoryMap". They just have different typeKeywords to uniquely identify them.

They all looks fairly similar in terms of being json items with a few resources. This issue is to test if our current support StoryMap Stories also works for Collections and Briefings.

Essentially what we want to test for each stories, collections, and briefings:

- Create the story map and have it reference a web app and survey (ensure sharing is private)
- Create a group and share the story map, app and survey with the group
- Create a solution item from the group
- Deploy the solution item to a different org
- Verify all the items were deployed properly and the app and survey are properly embedded/referenced in the story map.

**Comment by skrishn** [comment]
@chris-fox I tried it incognito, but both the survey and app prompted me to log in for Storymap, Briefings, and Collections. If I publish in the destination org, it works.

**Comment by chris-fox** [comment]
@skrishn, could you share the solution item that created to deploy that shows this issue? I would like try deploying it into a different org and see why it is failing. It seems to be an issue where the draft is working properly but the published version is not.

**Comment by skrishn** [comment]
@chris-fox:

**For StoryMap, Briefing and Collection:**

When we first launch the story/briefing/collection

1.	It points to the app URL in the deployed org
2.	It points to the origin org’s Portal URL with form ID from the deployed org. 
3.	Later, it makes requests to the Solution Item’s origin org for the app and survey. App prompts to login to the origin org, and the survey fails because uses the wrong portal URL and wrong form ID. 

**In Edit:** 

**Draft JSON**

1.	For the App:
a.	It points to the deployed org’s app. 
https://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=0917341af367442ca9e0ae63ba9cc274
2.	For the survey:
a.	It points to the origin org’s Portal URL and the form id from the deployed org
https://survey123.arcgis.com/share/?open=web&embed=fullScreen&portalUrl=https%3A%2F%2Flocaldeployment.maps.arcgis.com&id=d82adbab718b4e05ae1dd0e1fdbc3153&hide=navbar,footer,theme

**Published_data.json**

1.	For the App:
a.	It points to the origin org’s URL and app ID
https://localdeployment.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=b44b75bf7cde459fa77c5d18204b2823
2.	For the survey:
a.	It points to the origin org’s Portal URL and form ID in the Origin org.
https://survey123.arcgis.com/share/?open=web&embed=fullScreen&portalUrl=https%3A%2F%2Flocaldeployment.maps.arcgis.com&id=b29c23a24c874b03bf022d568115f815&hide=navbar,footer,theme

**After re-publishing:**

**Published_data.json**

1.	For the App:
a.	It points to the deployed org’s app. And, so, it works correctly
https://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceManager/index.html?appid=0917341af367442ca9e0ae63ba9cc274
2.	For the survey:
b.	It points to the origin org’s Portal URL and the form ID from the deployed org.
https://survey123.arcgis.com/share/?open=web&embed=fullScreen&portalUrl=https%3A%2F%2Flocaldeployment.maps.arcgis.com&id=d82adbab718b4e05ae1dd0e1fdbc3153&hide=navbar,footer,theme

**Comment by chris-fox** [comment]
@skrishn, i logged 2 new issues for this #1298 and #1299 that should address what you found. Going to close this issue.
