### ISSUE TITLE
Data in other organizations can't be used in solution item. 

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#171]
Not sure if we have a plan for this. 

Currently, we have many State and EM solutions in the state-em-deploy org and there are plans to have some of these migrated to localdeployment.maps.arcgis.com. 

If those solutions are added as items to the localdeployment org and they reference groups or layers in a different organization (ie, a Reporter Configuration migrated to localdeployment, but group and data are still in the state-em-deploy), the solution fails to deploy. 

For the immediate future, this isn't an issue because we can make sure all data is present in a single organization. However, when we allow users to author solutions, this may come up. 

As Esri pushes more towards open data and sharing layers, users will want to use data outside their organization (other than living atlas) to extend maps and ultimately, custom solutions.

Do we have a plan in place for copying data (layers, groups, etc) without trying to swizzle them? I would see this process as: check if owner/admin, if not owner/admin, copy exactly, else, copy with variables added as necessary.

**Comment by chris-fox** [comment]
@shoe913, it will be a requirement that when a user authors a solution template from items that they are either the owner of the items or admins in the org. This is because some items will require admin access in order to pull their full definition into the template. Items referenced from other orgs or without admin access should not be templatized and should be referenced as is, w/o being replaced with variables.

We probably need to add this logic though as per your last comment. Specifically for living atlas content we need to support those being passed as reference in the template rather than being swapped out with a variable. If this isn't behaving correctly could you please log an issue.

**Comment by shoe913** [comment]
@chris-fox 

Thanks for the info. It looks like Living Atlas layers aren't behaving correctly. I've logged this as #173
