### ISSUE TITLE
Ignore Living Atlas Feature Services during templatization

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#173]
If a Living Atlas Layer is in a solution, the solution template cannot be deployed because the layer cannot be cloned. Deployment hangs indefinitely. 

Sample: "Living Atlas Test" 
https://localdeployment.maps.arcgis.com/home/item.html?id=3a052dbe96574a9ca37c3160c3a4269d

In the JSON, the URL parameter and ItemID are being turned into parameters 

"operationalLayers": [
                    {
                        "id": "NDFD_Precipitation_v1_858",
                        "layerType": "ArcGISFeatureLayer",
                        "url": "{{f9e9283b9c9741d09aad633f68758bf6.layer2.url}}",
                        "visibility": false,
                        "opacity": 0.65,
                        "title": "National Weather Service Precipitation Forecast - Cumulative Total",
                        "itemId": "{{f9e9283b9c9741d09aad633f68758bf6.layer2.itemId}}"
                    },"

**Comment by chris-fox** [comment]
@shoe913, Could you try changing that operational layer url property and itemId property back to what they were originally in the web map. Then for that template remove the 'f9e9283b9c9741d09aad633f68758bf6' reference from the depedencies. Finally remove the 'f9e9283b9c9741d09aad633f68758bf6' template from the templates array and save the changes to the json. When you deploy does it create the web map correctly and just reference the living atlas layer.

I ask because one thing I am considering for June is prioritizing Deployment bugs over Template authoring bugs. If for example we have to help the Solution author manually repair their template and it will deploy properly, this is something we could ship with. Its not ideal, but we can continue enhancing the template authoring logic after the first release. Whereas if it won't deploy this is more of a showstopper.

**Comment by chris-fox** [comment]
@jmhauck, could you investigate what it would take to determine if the authoring user has admin access to the item (Is the owner or is an admin in the org the item belongs to). Then what would it involve to either not templatize the item or partially templatize it as an external resource depending on if this would need to before or after the depdencies and variables have been set on the parent item. Would like to discuss more after this investigation to decide on the best approach.

**Comment by shoe913** [comment]
@chris-fox 

Those changes did get the item to deploy correctly. 

I agree, for the first release we can certainly have our folks manually make these changes to the JSON. Since we couldn't do this with the pro addin, I think only new solutions will need this and that will be a small number.

**Comment by chris-fox** [comment]
@jmhauck, There is a property returned on the item called itemControl, it is optional. Per the documentation:

Values: admin (for item owner and org admin) | update (for members of groups with item update capability that the item is shared with)

So we need that property to be admin in order for the item to be something we turn into a template.

https://developers.arcgis.com/rest/users-groups-and-items/item.htm.

**Comment by chris-fox** [comment]
After discussion with @jmhauck, last night we are going to do 2 things here:

1. When a feature service item is found we will check its item properties, if it has the property "groupDesignations" and it is set to "livingatlas", we should ignore it, not templatize it, and not include it in the dependencies. This item property corresponds to the living atlas badge show on the items:

![image](https://user-images.githubusercontent.com/6796763/76102310-d1a55900-5f9d-11ea-978b-26cd78a06ec3.png)

2. The only items we truly need admin access to is hosted feature layer join views. In the scenario where we encounter a hosted feature layer join view during template creation that we don't have admin access to, I would like the template creation process to fail with an error. I feel it is better to fail then ignore it and proceed as it may be difficult for the user to know that it didn't actually include their view.

**Comment by shoe913** [comment]
Verified
