### ISSUE TITLE
Should Non-GIS content be referenced or copied?

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#177]
Not sure if there has been discussion on this already. 

I added a word doc, PDF, PNG, and JPG to a group and made a solution item. When deployed, links to the original content were added to the organization. 

If this method is used to deliver supplemental materials for a solution, would we want to clone these to the organization? 

Depending on what the update pattern for a solution item is, I can see arguments for each scenario.

**Comment by chris-fox** [comment]
@shoe913, it should copy these item types to the user org. I tested your Non GIS solution and found the items were copied to my org. The Solution Item links to the deployment org items, but that is because of #170. The actual items created in my org I can download and view. Could you please verify you see the same.

**Comment by shoe913** [comment]
@chris-fox 

I do see the same thing. I brought this up because #170  threw me for a loop and I wasn't 100% sure what we would want for default behavior. 

Since this is working as expected, I'll close this out.
