### ISSUE TITLE
Support for Tracker

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#180]
This is dependent on :  #173  #112 and maybe #129 

When tracker is in an organization, a single layer is laid down and views are created off of this. New solutions using tracker employ notebooks to create views of this tracker layer. 

Workflow for deployment would be as follows:
1) Check if Tracker Layer exists / if tracker is enabled in org
  - If not enabled, message that solution can't be deployed
2) Create view of tracker layer
  - User deploying may not be the owner of the tracker layer, handle as necessary
3) Swap new view and tracker layer into the solution / python notebook.

**Comment by chris-fox** [comment]
@shoe913, this is more complicated. Right now views can only be created in the user content who owns the source service. So only admins can create views on the tracker service, because they may need to create it in another user's content.

There is talk of a new privilege that can be assigned to specific users to allow them to create track views so they don't have to be administrators, but this isn't there yet.

I think we need to think more about this before we implement this and ultimately what we want the user experience to be if they open a solution that requires tracker and they don't have these privileges.

**Comment by shoe913** [comment]
OK, sounds good. I know there are quite a few moving parts in there. 

Primarily, I wanted this issue created so it wouldn't fall of our radar.

**Comment by chris-fox** [comment]
Done
