### ISSUE TITLE
"created" and "thumbnail" property does not exist in JSON returned from deployer.deploySolution

### ISSUE THREAD

**Issue by cosbyr** [Esri/solution.js#204]
Solution deployment app depends on these properties existing on the returned card.

**Comment by MikeTschudi** [comment]
@cosbyr, I created the following signature for deployment:
```typescript
function deploySolution(
  templateSolutionId: string,
  authentication: common.UserSession,
  options?: common.IDeploySolutionOptions
): Promise<string>
```
A subsequent query into solution.js would get you item information that you need. But what would you prefer?

---

Separately, how would you like to have a job-number request given the Promise-based interface, please?  One idea that I thought of was for we could add an app-supplied id in the IDeploySolutionOptions; we have a routine that generates an 8-character random id, e.g.

---

IDeploySolutionOptions is defined as
```typescript
interface IDeploySolutionOptions {
  title?: string; // default: copied from solution item
  snippet?: string; // default: copied from solution item
  description?: string; // default: copied from solution item
  tags?: string[]; // default: copied from solution item
  thumbnailUrl?: string; // default: copied from solution item
  templateDictionary?: any; // default: {}
  additionalTypeKeywords?: string[]; // default: []; supplements ["Solution", "Deployed"]
  progressCallback?: ISolutionProgressCallback;
}
```

and ISolutionProgressCallback is defined as
```typescript
type ISolutionProgressCallback = (percentDone: number) => void;
```

deploySolution resolves with the deployed solution id or rejects with a structure such as
```typescript
{
  success: false
  itemIds: ["b1c3fd3061de44afbaffd6241ddc8766"]
  error: "One or more items cannot be deployed"
}
```
which reports the item(s) causing failure.  Because a failure short-circuits processing, there may be additional items that will fail but didn’t get the chance.  Failure deletes everything created.

**Comment by cosbyr** [comment]
@MikeTschudi 
In order to get the information I need do i need to a [getItemInfo](https://esri.github.io/solution.js/api/common/getItemInfo/) call with the returned Id? If so... That works for me.

Regarding the job number request. I think it makes sense to have it as an additional property of the IDeploySolutionOptions as you have proposed. Would the deployer.deploySolution return that jobID value back somehow? I'm not clear on how I would get that value back.
