### ISSUE TITLE
Cannot Create Gallery App Solution Templates

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#206]
Called COP in the deploy org. Failure indicates a dependency is wrong. 

Will create new group and narrow down to specific items causing issue

![image](https://user-images.githubusercontent.com/11777080/74850793-3e0e3000-52ef-11ea-983e-88b593326b46.png)

**Comment by shoe913** [comment]
Issue is caused by the Common Operational Picture Gallery App.  Given the error, this makes sense. 

@chris-fox 
As gallery apps will not be required for solution items, not sure how we want to proceed with this. 

Currently, we use the gallery to help deploy items with the SDT in Pro and I assume these apps also help organizations as an easy "go-to" location for launching the parts of a solution. 

Given that it makes easy access to apps, I think we would want to address this because the functionality is used for more than just deployment.

**Comment by chris-fox** [comment]
@shoe913 Yes, we should look into why the Gallery App is failing. I would think it should behave the same as Crowdsource Reporter or Manager, because it is just another group application template and has the same basic json definition. Could you try with a simple gallery app to provide an easy repro case?

In terms of whether we deliver the gallery app with the Solutions, I think it will be up to the solution owner. Personally I think the Solution item and the links in the item details helps with organizing the content in the Solution, but if people want to ship it with the Solution they should be able to.

**Comment by shoe913** [comment]
Looks like this happens with other gallery apps as well. 

Both the Minimal Gallery and the Category Gallery fail to create correctly. They get the same error in the console and both create an empty Solution Template.

The apps only have a single item in the group shared so they are pretty simple.

**Comment by shoe913** [comment]
@jmhauck 

After sorting out #175, can you take a peek at this? I believe this used to work, so hopefully won't be too bad to fix.

**Comment by shoe913** [comment]
Fixed
