### ISSUE TITLE
Security Scans for Creation, Deployment, and Solutions App Use

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#234]
Add HTML sanitizers to ensure clean solution templates. This will be done on template creation and solution deployment. 

Template: Description, Snippet
Info Products: Description, Snippet, Pop-up codes

**Comment by chris-fox** [comment]
@shoe913, Makes sense for description and snippet. I worry about changing the pop-ups thought. The web map viewer should do this automatically when you save. I don't want to break the pop-ups as part of this process.

**Comment by shoe913** [comment]
@chris-fox 

Our concern with the pop-ups is in regard to users injecting their own html (similar to our standardizing processes) into their Solution's JSON. If this happens anything can be put in and won't be sanitized until the map is opened and saved. 

This may be a fringe scenario, but the fact that we are already doing a similar workflow proves it could be a potential hole. 

I'm not aware of workflows in place which prevent this at REST to the webmap, however those maps won't potentially end up in another organization.

**Comment by chris-fox** [comment]
@shoe913, how are we going to know what is valid and what is invalid html? AGO has specific rules that I am not sure we have ensure we are following their rules and not over doing it or under doing it. Also this is something users can easily do today to their own webmaps so I am not sure why we feel we need to solve this problem.

**Comment by dbouwman** [comment]
Fwiw - I've done a little poking around w/ the [jsxss](https://jsxss.com/en/index.html) lib that backs the [arcgis-html-sanitizer](https://github.com/Esri/arcgis-html-sanitizer) module, and it can be fed a object, and it applies the sanitization rules to all string fields down the whole graph. 

We are looking at switching to this in Hub because it is a more wholistic solution we can apply on every save and load vs handling sanitization at edit time on specific card properties. 

We have more testing to do to ensure we can extend it for aria bootstrap props not in the base lib's rules, and that it does not mess up other stuff... but I think it may be a clean option for Solutions - just run the entire solution /data thru it before deploying

**Comment by MikeTschudi** [comment]
@shoe913, PR #295 has initial solution scanning

**Comment by MikeTschudi** [comment]
#321 is caused by blindly scanning the data section of items; as @dbouwman wrote, "TODO: we should delegate data sanitization to the type-specific modules"

With PR #325, restricting scanning to the item base info; issue #324 takes over data section sanitization.

**Comment by shoe913** [comment]
Verified
