### ISSUE TITLE
Solution Item Thumbnails are not maintained with the Copy App

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#242]
This only appears to happen with solutions made in the last few days. 

Thumbnails are maintained on older solutions.

**Comment by MikeTschudi** [comment]
It works if the source item is public. Looking into how token can be used when fetching image from source.

**Comment by shoe913** [comment]
Verified

**Comment by chris-fox** [comment]
I am seeing this issue again, when i look at the request i am getting an invalid token in the url request for the thumbnail.

**Comment by MikeTschudi** [comment]
Commit 46808926cf974839fb2fc20190d04e30667e82e6 changes thumbnail tokens to get the token as needed, rather than at the beginning of the copy. This allows for token refreshes.

Unfortunately, this probably causes some of the addResources calls to stall with 502 server errors when a lot of large solutions (e.g., more than 10) are copied at the same time while the browser network speed is set to "Slow 3G" (and sometimes "Fast 3G"). I think that it's still an improvement.

**Comment by shoe913** [comment]
Verified
