### ISSUE TITLE
ArcGIS Enterprise support

### ISSUE THREAD

**Issue by DBruzas** [Esri/solution.js#302]
Currently the API works on ArcGIS Online. Will this be extended to ArcGIS Enterprise as well?

**Comment by chris-fox** [comment]
@DBruzas, yes we will support Enterprise. It will probably work today, however if you try to create a solution from Online and deploy to Enterprise it may fail primarily due to incompatibilities in Feature Services. We have future work planned to during a template creation create a definition of the feature services that is compatible in Online or Enterprise.
