### ISSUE TITLE
Improve messaging in console when Solution Item fails to create

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#307]
Some Solutions contain references to layers which no longer exist. When these solutions turned into solution items, they fail because the layers no longer exist. 

ex.
https://localdeployment.maps.arcgis.com/home/item.html?id=8130653f73f14e3488effbfa1f65f093

We need to be able to handle the vestigial services to ensure everything can be created correctly.

**Comment by chris-fox** [comment]
@shoe913, @jmhauck, I changed my mind on this. Recently I had a the Create tool fail because of a non-existent service that actually was causing the app to break. So having fail was actually helpful in knowing there was an issue with the app. 

So I don't think we should to successfully create a new solution item. However, I would like to see better info reported to the console, specifically, what item it failed on would be helpful in debugging these issues.

@shoe913, I resolved the issue in the Neighborhood Crime Reports app, the property wasn't referenced anywhere else in the app so I just removed it.. Could you please let Chris D. know that he should know be able to create a solution item from it.

**Comment by shoe913** [comment]
@chris-fox 

Will do. If/when we encounter this again, I'll address the item as necessary.

**Comment by shoe913** [comment]
Verified
