### ISSUE TITLE
Deployment process does not create domains 

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#322]
When deployment unpacks a feature with a domain (see Citizen Problem Reporter), the domains aren't created. They are present in the JSON of the feature service. 

This could be related #321 . What is causing the SVG to not be fully parsed could have a cascading effect on the domains.

**Comment by chris-fox** [comment]
This is an issue when Feature Layer Views have different domain definitions then the source service. @jmhauck originally did this work. Assigning to him. The key is if a view has a different domain definition for a field then the source it needs to be applied in an update after the view is created.

We only want to do this on fields that have different domains then the source, otherwise it breaks the connection with the source domain.

**Comment by shoe913** [comment]
Verfieid
