### ISSUE TITLE
Variables stored in License Information Don't always get swizzeled

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#383]
1) Deploy the "Andy Health Planning Test Deploy" Item.
2) On the Crowd Control item, the license information has a variable in the URL
3) Deploy the Swizzle test"
4) On the Credits Check item, the variables used have been swizzeled

Not sure if this is because the variable is in a URL or based on item type. Regardless, it should be swizzled. Will continue testing to narrow down issue

**Comment by chris-fox** [comment]
@shoe913, try making the item that needs to be swizzle a dependency of the Crowd Control item. It may not be doing a second pass for item details.

**Comment by shoe913** [comment]
@chris-fox 

That fixed the issue on the larger solution item.  The other item however, does not have the dependency listed. 

This might be a good work around for now, but I think we may want a cleaner way forward sinceit seems a little inconsistent.

**Comment by chris-fox** [comment]
yea, just trying to avoid any changes for UC if we have a workaround for now.

**Comment by chris-fox** [comment]
This request is to do a second pass on the item properties, not just the data.

**Comment by MikeTschudi** [comment]
There were two problems with this example
1. The variable in `licenseInfo` was spelled `itemid` instead of `itemId`.
2. As @chris-fox mentioned above, the QuickCapture item didn't have the Dashboard item in its list of dependencies, which risks that the QuickCapture item will be created before the id of the deployed Dashboard item is known.

Both cases can lead to the replacement symbol not findable, leaving the `licenseInfo` unchanged. Once these two corrections are made, `licenseInfo` is replaced.

@shoe913, would you please check that it works for you, too?

**Comment by chris-fox** [comment]
@MikeTschudi, yes we were able to work around this. However, the issue is sometimes we may have circular dependencies that need to be resolved, for example #298, that can't rely on dependencies.

We currently handle this by doing a second pass after all items have been created to see if any variables still exist in an item's data and update.

The request in this issue is to extend this logic to also look in the item's info/details for unresolved variables in the second pass.

**Comment by MikeTschudi** [comment]
Resolved for "Andy Health Planning Test Deploy" test case. Moving broader request to new issue #444.

**Comment by shoe913** [comment]
Verified
