### ISSUE TITLE
${itemId} not being replaced for logo and icon URLs

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#433]
Deploying [My Trash Services](https://arcgis4localgov2.maps.arcgis.com/home/item.html?id=6ac8a7d46d364d9aa4fcacc4cb8738eb) yields a web mapping application with
```
"logo":"https://arcgis4localgov2.maps.arcgis.com/sharing/rest/content/items/${itemId}/resources/inConfig/15773132244315513.png"
"icon":"https://arcgis4localgov2.maps.arcgis.com/sharing/rest/content/items/${itemId}/resources/inConfig/4980549869197164.png"
```

**Comment by chris-fox** [comment]
@MikeTschudi, this is expected behavior with WAB. ${itemId} is their way of creating a relative path to itself. How they get access to resources of the app itself. We shouldn't swizzle anything.

It is different from our variables of double curly braces. If you open the app you will see both the app logo and widget icon properly resolve to the corresponding resource:

![image](https://user-images.githubusercontent.com/6796763/90663957-57e5ec80-e218-11ea-92da-a06e1f861297.png)

**Comment by MikeTschudi** [comment]
Thanks, @chris-fox!
