### ISSUE TITLE
Add check in item's info/details for unresolved variables to post processing

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/solution.js#444]
Chris: The issue is sometimes we may have circular dependencies that need to be resolved, for example #298, that can't rely on dependencies.

cf. #383

A function `postProcess` performs a second-pass check on the `data` property
```typescript
return getItemDataAsJson(itemId, authentication).then(data => {
  if (hasUnresolvedVariables(data)) {
    const updatedData = replaceInTemplate(data, templateDictionary);
    // TODO: update return type on updateItemExtended
    return updateItemExtended(
      itemId,
      { id: itemId },
      updatedData,
      authentication
    ) as Promise<any>;
  } else {
    return Promise.resolve({ success: true });
  }
});
```
in each of the notebook, quickcapture, simple-types modules.

With this issue, we also check the `item` property as is done with feature-layer's `postProcess` function.

**Comment by chris-fox** [comment]
@MikeTschudi, I can still reproduce this with a quick capture project:

8c6fa046e2c042ab9f8dae9972323351

The quick capture project has a couple variables in the Terms of Use:

![image](https://user-images.githubusercontent.com/6796763/93361616-0d559100-f813-11ea-8696-766aa8ce2f56.png)

When deployed the portalBaseUrl is replaced, but the itemId variable of the Dashboard also in the solution is not replaced.

Moving from the 8.3 project because it is not critical for this release.

**Comment by chris-fox** [comment]
Verified
