### ISSUE TITLE
Fail to deploying feature service to Enterprise, 'sourceSchemaChangesAllowed' cannot be updated.

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#449]
This solution fails when attempting to deploy to Enterprise when creating a feature service called 'Workforce'. 

da0765bd3d0e46519bb1291492edabcb

In the update call we are passing 'sourceSchemaChangesAllowed': true and the error returned is you are not allowed to update this property.

It doesn't seem like we need to pass this in the updateDefinition request as it is in the original addToDefinition request.

**Comment by jmhauck** [comment]
After removing sourceSchemaChangesAllowed it was still failing. Not a message that stated it directly as it did with sourceSchemaChangesAllowed but I found that I also needed to remove isView (set when you create the feature service). After that it was also failing when the initalExtent for the table was null so that is also now removed when going to portal when it comes in as null.

**Comment by chris-fox** [comment]
thanks @jmhauck, appreciate you running all those down.

**Comment by chris-fox** [comment]
Verified
