### ISSUE TITLE
Repair field index during solution creation if used as key field in relationship

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#455]
If a solution Item has a layer with 2 relationship classes and the same key field is used, the deployment fails when updating the layer with the relationships. 

The error states
The operation failed because an index or statistics with name 'agency_case_number_unidx' already exists on table 'sh_db_27881.user_43804.UseOfForce_100527e76a5a474985107788af5fda94_INCIDENTS'.

This does not exist in the indices or statistics for the solution. When the key field is changed, deployment occurs correctly. 

See "Andy Create Test" for test case of failure
https://arcgis4localgov2.maps.arcgis.com/home/item.html?id=4a02d12657824677b6362f9fc0712223

**Comment by chris-fox** [comment]
This is because the layer that has a relationship in which it is the origin has a non-unique index on the key field in the relationship. When you add a relationship to a layer it will attempt to add a unique index and because the layer already has a non-unique index on the same field it will fail.

I believe this is easily resolved in the template by changing the "isUnique" property from false to true.

I think what we could do is resolve the definition of feature service during creation, by looking if a layer has a relationship, if it is the origin, and if it has an index that is on the key field that we automatically set the index 'isUnique' to true.

"relationships": [{
"id": 0,
"name": "",
"relatedTableId": 1,
"cardinality": "esriRelCardinalityOneToMany",
"role": "esriRelRoleOrigin",
"keyField": "agency_case_number"
"composite": false
}]

"indexes": [{
"name": "G5agency_case_nu",
"fields": "agency_case_number",
"isAscending": true,
"isUnique": false,
"description": ""
}]

**Comment by chris-fox** [comment]
Looks great
