### ISSUE TITLE
Feature service failing to deploy with long name

### ISSUE THREAD

**Issue by ghudgins** [Esri/solution.js#529]
STR:

I'm guessing at the culprit below. @dbouwman thinks there are two things happening (and solutions is swallowing the error opaquely). The tempalte I'm trying to deploy is available on this item in production as ghudgins5 / wally11turtle! http://eapsprod.surge.sh/items/b52003806ab94f06b4ee3452a9983d3c/edit

Fails with
![image](https://user-images.githubusercontent.com/5465514/97316185-d7f38880-183f-11eb-816e-63aefbb46c06.png)

**Notes:**

* input layer has this `itemId` in a layer 

![image](https://user-images.githubusercontent.com/5465514/97316061-babeba00-183f-11eb-8f13-c3a57dec5923.png)

* convert to template outputs this (successfully)

![image](https://user-images.githubusercontent.com/5465514/97316158-cf9b4d80-183f-11eb-957d-6ea26cb7e19c.png)

* deploy fails

![image](https://user-images.githubusercontent.com/5465514/97316185-d7f38880-183f-11eb-816e-63aefbb46c06.png)

**Comment by ghudgins** [comment]
there's also a `{success: false}` coming back from the `createService` API

**Comment by chris-fox** [comment]
This is failing attempting to create the service as you found. It looks like it is happening because of the long name:

"name": "Travel_from_Transportation_WebMercator___Metro_Stations_(District)_(10_Minutes)_b9fa0f3ded304a04ac07a39704a5b81c",

I was able to repro the createService failure through the Home app with the same name. 

The issue is we always append the itemID of the Solution to any features services and views we create to gaurantee the service name is unique. It seems since this service already had a long name that adding the guid put it over the top to where it fails. If you edit the template to reduce the name length it will likely fix it.

I think the fix should be to set a max length (need to determine what this is) of the feature service name, and we truncate the original name if necessary, but keep the _guid to ensure uniqueness.

**Comment by ghudgins** [comment]
interesting....i did try a shorter name in a curl  and still got the failure. thanks for triaging @chris-fox

**Comment by chris-fox** [comment]
@jmhauck, I found the limit in online was 98 characters and was similar in enterprise. I think we should go shorter to be safe, so I would say we limit the name to 50 characters prior to appending the __GUID_, which would add an additional 33 characters for a total of 83. So anything in the original name greater than 50 characters should be dropped when creating the new name for the service.

**Comment by chris-fox** [comment]
@ghudgins, I had to change the name property on the feature service in the template to a shorter name and it worked. For example i just changed it to "Travel_from_Transportation_WebMercator"

![image](https://user-images.githubusercontent.com/6796763/97334399-16467300-1853-11eb-818c-597f00f1ff7d.png)

**Comment by chris-fox** [comment]
Working well
