### ISSUE TITLE
Revisit Cyclical Dependencies for Creation Process

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#561]
Dependencies created by arcade in Maps and Layers are creating cyclical paths which cannot be deployed or displayed.

Ex: arcgis.com/home/item.html?id=4b8321df1bcb4f90abde8fa8536aca0f

**Comment by chris-fox** [comment]
@shoe913, @MikeTschudi, do we know if this issue is occurred in the version of solution.js included in the most recent release that went out in 8.4?

Could we update the Create app to use the version of solution.js that was included with 8.4 and keep it locked at that version? That way for everyone who is creating and deploying solutions (released app) will be at the same version of solution.js

We can certify creation fixes, test bugs using the demo app that is built from develop.

**Comment by MikeTschudi** [comment]
@chris-fox, @cosbyr made sure that the solution-deployment-app and solution-creation-app were synchronized with respect to their use of solution.js as a submodule. We can create a release/agol-8.4 branch to lock that state.

**Comment by shoe913** [comment]
verified
