### ISSUE TITLE
common.deleteSolution() function

### ISSUE THREAD

**Issue by cosbyr** [Esri/solution.js#624]
For the June release we need a function in solution.js that will Delete a solution item and all of its dependencies (feature services, views, apps, groups, and containing folder if possible)

I'm thinking this would all under the `common` package and would have the following signature:

```ts
export function deleteSolution(
  solutionItemId: string,
  authentication: common.UserSession,
  options?: common.IDeleteSolutionOptions
): Promise<string> {}
```
`common.IDeleteSolutionOptions` would be formatted similar to `common.IDeploySolutionOptions` and would be leveraged to report back deletion progress.

**Comment by MikeTschudi** [comment]
Implementing in three phases:
* [ ] Write deployed items into deployed Solution in build order (metadata.version "1")
* [ ] Delete metadata.version "1" Solutions
* [ ] Re-create build order when metadata.version "0" (current) Solutions are to be deleted, and delete them

**Comment by cosbyr** [comment]
@MikeTschudi 

Not sure if you are already doing this, but thinking it would be a nice bonus to the user if we delete the folder the solution is contained within upon a successful deletion. Would need to check that the folder is completely empty before doing that of course :)

**Comment by MikeTschudi** [comment]
@cosbyr, makes sense; will add to project.

Groups aren't being deleted, either.

**Comment by cosbyr** [comment]
@chris-fox Do we want groups deleted also?

**Comment by chris-fox** [comment]
@MikeTschudi, @cosbyr, I was thinking a little about this and my concern with deleting groups is there was no way to know if it was shared/used by another solution, but I think I have a good solution. If there are no items shared with the group we can delete it. We would have to do this after everything else is deleted from the solution, check if the groups have any items still shared and if not delete them. Thoughts?

**Comment by cosbyr** [comment]
@chris-fox That sounds like a good call to me. If group is empty of items after solution deletion, delete the group, otherwise don't.

**Comment by MikeTschudi** [comment]
This matches the approach that Ryan suggested for folders. Only catch might be the latency between AGO reporting success and AGO actually completing a task; time to experiment!

**Comment by MikeTschudi** [comment]
* [ ] Don't delete items shared outside of the Solution
* [ ] Delete Solution deployment group iff empty

**Comment by MikeTschudi** [comment]
Update to API from Ryan:
* [ ] Delete deployed Solution item as long as none of its items fail to be deleted, including case where a Solution shares ALL of its related items with another Solution (e.g., Daily Activity Dashboard, Multi Source Data Feeds)

Exception to returning two lists of successful and failed deletes is case where Solution is not deletable (solution templates, etc.), in which case `deleteSolution` returns [undefined, undefined].

**Comment by MikeTschudi** [comment]
A note about deleting folders: when two Solutions share an item, a Solution folder might not be deleted.

For example, if you deploy Road Closures and then Special Event Operations, SEO shares a feature service that's stored in RC's Solution folder.

Now delete the Road Closures Solution. All but the shared feature service will be deleted, and because the RC Solution folder is not empty, its folder will not be deleted.

Now if you delete SEO, the shared feature service will be deleted because it is only used by SEO even though it is in the RC folder. The SEO folder becomes empty and is deleted. The RC folder will also become empty, but because it is not the SEO folder, it will not be deleted.

@shoe913, @chris-fox, If we want to have a more complete deletion, we could store the containing folder for each item that is deleted, and then delete all of those folders at the end (if empty) instead of just the folder of the currently-being-deleted Solution.

**Comment by shoe913** [comment]
Thanks, @MikeTschudi 

Would moving the shared items also be a potential workflow?

In your scenario, instead of just leaving the shared layers in the RC folder and deleting them later, could we move them to the SEO folder? We know they are shared because of the Solution2Item relationship. We could just find the parent folder id for the SEO solution item and then move the shared resource there before deleting the RC folder.

I'm not sure of the overhead this would require, but I think it may be a nice user experience to not have folders with 1 or 2 items.  This would also prevent those extra folders from hanging out and causing confusion ala --"I deleted the solution, but the folder is still there....what went wrong?"

**Comment by MikeTschudi** [comment]
That's a really good idea @shoe913!

The overhead would be low--just an extra item fetch, I believe, which is quick.
* before deleting an item, get its Solution2Item relationships
  * if only 1, OK to delete
  * if 2, don't delete
    * fetch Solution item indicated by relationship to Solution not being deleted to get its folder
    * move item to that folder
   * if >2, don't delete

**Comment by chris-fox** [comment]
My initial reaction is I am hesitant about moving items in a user's content. In the scenario below maybe they have other content in the Road Closures folder intentionally and want it to sit with the Road Closures layer. As a user it could be confusing to me if I went to that folder and found the service was no longer there. In addition, what if the shared Solution item had been transferred to a different owner? We wouldn't want to transfer ownership of the item and might not have permission to do so anyway.

I am leaning towards keeping the logic as is or Mike's idea of deleting an item's folder if it is empty after all items have been deleted. That seems safer to me.

**Comment by chris-fox** [comment]
Verified
