### ISSUE TITLE
Deploying updated version of solution is failing

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#650]
Steps to repro:

1. From the production app "https://www.arcgis.com/apps/solutions" deploy Daily Activity Dashboard
2. From the Certification app "https://solutionstest.esri.com/online-certify/index.html" deploy the updated version of Daily Activity Dashboard.

It will fail with the following console error:

![image](https://user-images.githubusercontent.com/6796763/120665419-bef82900-c459-11eb-808a-9a1395999022.png)

**Comment by MikeTschudi** [comment]
Using solution.js release v0.23.0's deploySolution demo, the call to `deployItems.deploySolutionItems` in deploySolutionFromTemplate.ts returns a list of deployed items as expected:
![image](https://user-images.githubusercontent.com/2125181/120684186-42624c00-c453-11eb-9ee1-e8e766747a64.png)

Using solution-deployment-app commit 07e3ba2c5b7fc1789cb349a2f5863440a1323228 (which uses solution.js v0.23.0), `deployItems.deploySolutionItems` returns a list of deployed items that is missing the item details:
![image](https://user-images.githubusercontent.com/2125181/120684135-34acc680-c453-11eb-8c70-46ab7c092352.png)

The failing `map` call is accessing an item's dependencies, but since the item itself is null, its dependencies list doesn't exist, either.

Same solution; same library; different outcomes.

**Comment by chris-fox** [comment]
@MikeTschudi, in your test with the demo, did you enable the Use Existing Items option when you deployed the updated item? This might be the difference between what the test app is doing and the demo app.

![image](https://user-images.githubusercontent.com/6796763/120690128-d0016400-c472-11eb-8809-ab17dbbec533.png)

**Comment by MikeTschudi** [comment]
@chris-fox, I just found that out:  that is the breaking point

**Comment by MikeTschudi** [comment]
Flaw introduced with switch to sorting deployed Solution's template items in build order.

**Comment by chris-fox** [comment]
Verified
