### ISSUE TITLE
Items with Circular Dependencies fail to show Item Tree

### ISSUE THREAD

**Issue by shoe913** [Esri/solution.js#652]
A solution item where 2 items reference each other as a dependency fails to display an item tree.

In the item below, the survey has a word doc as a dependency and the word doc has the survey as a dependency. 

Group: https://localdeployment.maps.arcgis.com/home/group.html?id=8a8c06f28e4e4d9c8e37ad0627417e68 
Item: https://localdeployment.maps.arcgis.com/home/item.html?id=60b1326884154f5b9ce4d971c3bbf59d

**Comment by chris-fox** [comment]
This seems to impact all Surveys authored with Survey123 website. The services or other items used by the Survey123 form will have a typeKeyword of the Survey's item id. So the survey has a dependency on the feature service and the feature service has a dependency on the survey.

**Comment by chris-fox** [comment]
Note I tested and just removed the Form as a dependency of the service and when deploying the typeKeyword id variable was still swizzled in the service for the new Form. So it seems like we just need to prevent the service or other items that are dependencies of the survey from listing the form as a dependency.

**Comment by MikeTschudi** [comment]
Solution item 60b1326884154f5b9ce4d971c3bbf59d has an interesting dependency graph:
![image](https://user-images.githubusercontent.com/2125181/122822665-34a22880-d293-11eb-8347-1c928ca4c6bb.png)

The display algorithm looks for top-level items by finding the subset of items that are not dependencies of other items. With this Solution, *all* items are dependencies, and so none appear as top-level items--they're all filtered out.

**Comment by chris-fox** [comment]
@MikeTschudi, I believe this was introduced with this fix #534 

The issue is the MS Word has a typeKeyword with the item id of the Survey and the Survey has a relationship with the MS Word. In my mind I would prefer in this scenario that we see the Word doc as a dependency of the Survey, but the Word doc should not be a dependency of the Survey.

I would rather for #534 to not at any item references in the item info/details to the item's dependency and instead just use our post process routine for unresolved variables to look at an item's info/details.

This is actually the way it works today from my testing. If I manually edit the solution item above and remove the survey from the Word document's dependencies and then deploy, everything deploys correctly and the typeKeyword variable in the Word doc is successfully replaced at the end of the deployment.

**Comment by MikeTschudi** [comment]
Note that https://github.com/Esri/solution.js/commit/ef2fe72cbae120be847b01e48e94f2e3f1681159 will only affect solutions created in the future

**Comment by chris-fox** [comment]
@MikeTschudi, After this fix I am getting a console error attempting to create a solution item from group: 2efb053b7c424792ac9b611c3a32875f. It seems to create the item, but hadn't seen this console error before, so not sure what it is impacting.

![image](https://user-images.githubusercontent.com/6796763/123128559-401f5c00-d419-11eb-9f3c-c10e7cafdef3.png)

Also, I think I preferred the adding of dependencies during post-processing logic, I am just wondering if we can ignore dependencies found in the item's info/details? If a dependency is found in the item's data/json I think it does make sense and works well to add it as the item's dependency. Is this difficult to manage? 

This will make more sense for complicated items like ExB, Story Maps and Hub sites where we have lots of embedded content. And work around the issue above with Survey's and typeKeyword references.

**Comment by MikeTschudi** [comment]
The failure occurs when the app tries to display the details of the just-created Soultion; it stems from an inability to retrieve one of the created Solution's 157 resources and a disconnect between the failure and the createSolution app that causes the error message to be lost.

One or more zips are created for each source item's resources. In this Solution, there are many sources supplying resources, and so lots of small zips (47 1-file zips, one each of 3-, 4-, 7-file zips, and 2 41-file zips) are being sent to AGO, which can't handle lots of small zips sent rapidly just like it can't handle lots of resource files sent rapidly. The resources logic needs to be changed to queue all of the resources for the Solution item and then send them in one set of zip files (which may need to be spaced out when there are so many because of the AGO 50-file limit per zip).

For the dependencies, I think that we can achieve what you want by this simple code change, where light red indicates deleted code:
![image](https://user-images.githubusercontent.com/2125181/123493949-085c1400-d5d3-11eb-9a44-c2da40166276.png)

These are the two changes that I propose to make for this release. If all of the resources are successfully stored in the Solution item, the fetch error is not likely to occur.

---

In the longer term, the error-message disconnect needs to be fixed. The app shouldn't just show an error message (or fail to show anything like now) about the created Solution just because one or more resource fetches failed.

The [`Promise.all`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) used for fetching the resources (which requires that all promises succeed in order for the collection to succeed) should be changed to [`Promise.allSettled`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) (which allows for individual failures among independent actions, such as fetching resources from an item), but this requires us to update our build from es5 (5th edition of JavaScript in 2009) to es2020 (11th edition of JavaScript) or later. So not for 9.2, but worth looking into.

**Comment by shoe913** [comment]
Verified
