### ISSUE TITLE
IsViewOverride: true is being set on views for unknown reason

### ISSUE THREAD

**Issue by chris-fox** [Esri/solution.js#944]
@jmhauck, could you look into this one, I can't figure why IsViewOverride is being set on particular fields in a view when it doesn't appear that anything is overridden.

Deploy the Water Distribution Data Management solution. Check the resulting WaterDistributionSystem_viewing view. For the Service Connection layer, select the ObjectID field and it is set to isViewOverride: true. Comparing this field with the source I don't see anything different in the properties. This is true for several other fields, but not them all. It is not clear why this is occurring.

**Comment by chris-fox** [comment]
@jmhauck, saw you got a PR in thanks. Do you have any other information under what scenarios this issue occurred. I couldn't consistently reproduce it across all of our solutions. Just wondering how widespread the issue is, if it is a new issue since the last release and whether we should patch it in the current release.

**Comment by jmhauck** [comment]
The problem could exist on any Service\View combo that has multiple layers.

We store an array of the field names and associated values (for alias, domain, editable) that we compare between the source service and view. The problem was the field names array was being reused for all sublayers in a feature service. So when it went to check the ObjectID alias for one of the sublayers it was comparing to the first instance of ObjectID it found in the lookup. So if a service only had one sublayer we would have no issue. If the difference was the same across all sub layers for example ObjectID alias was always Object ID we would have no issue. The fix was to store them separately for each sub layer.

**Comment by chris-fox** [comment]
Verified in Dev and QA

**Comment by chris-fox** [comment]
Verified in Production
